### PR TITLE
Implement import to ConfigEntry

### PR DESCRIPTION
**Pull request by RobBie1221**
- Remove platform setup from domains
- Import yaml to ConfigEntry
- Implement loading/unloading of ConfigEntry
- Fix code quality issues

### CODE REVIEW

**Comment by RobBie1221** [comment]
@ksya I recently found myself in need of controlling my Nefit Easy from Home Assistant. I came across this integration and it works wonderful. I'm polishing it up a bit (config flow) and making sure it fulfills my needs. I've created a PR with the first set of changes I made, seemed fair enough to contribute what I did on my own system, if you think it's useful for the integration feel free to merge.

In this PR, I firstly ran everything through my HA development environment (pylint, flake8, isort, black) so that might explain some styling changes and minor code changes.
Furthermore I made the import from yaml to ConfigEntry. Next step is config flow, but with this PR in place that's not a whole lot of work. For existing users, this doesn't break anything.

I'm planning a few more changes, if you choose to merge this PR, I can push those as well:
- Implement user step in config flow
- Add a device for the entities
- Read the program details (not sure how yet, I basically need the active temp from current program to write into my radiator valves when overriding the nefit easy)

**Comment by ksya** [comment]
Great work! Thank you very much for this 👍 
The other changes you propose seem also very interesting.

**Comment by RobBie1221** [comment]
Thanks!

I'll push some more changes after the holidays.

**Comment by MHOMEASS** [comment]
Thank you!

**Pull request merged**
