### PR TITLE
Be able to switch program using preset mode selector

### PR DESCRIPTION
**Pull request by ksya**
Fixes https://github.com/ksya/ha-nefiteasy/issues/12

### CODE REVIEW

**Comment by RobBie1221** [comment]
I wonder if this may be too confusing, the mode was just simple manual/automatic, but with proposed change a user would have to think every time whether program 1 or 2 was active.

Could we maybe use the `preset_modes` of the climate entity to set the active program?

**Comment by ksya** [comment]
You can choose with this change between manual, clock1 and clock2 and maybe you are right. My girlfriend would not know if she should choose program 1 or program 2. But also, she will never change between clock and manual herself.
When does it matter what program was active? If you know what each program is, you can select the right one. Or in most cases, you can automate it.

I dont understand your last sentence, since it is now using the preset_modes.

**Comment by RobBie1221** [comment]
> I dont understand your last sentence, since it is now using the preset_modes.

🤦‍♂️ I thought we were setting HVAC mode, but you are right. My mistake.

> You can choose with this change between manual, clock1 and clock2 and maybe you are right. My girlfriend would not know if she should choose program 1 or program 2. But also, she will never change between clock and manual herself.
> When does it matter what program was active? If you know what each program is, you can select the right one. Or in most cases, you can automate it.
> 

Well this is exactly my point. Me and my wife both use that switch to go from Manual to Automatic (or Clock mode).
I personally don't like that in this proposed change, two endpoints are controlled with one switch. To me that reduces the transparancy of the functionality. In my opinion, we should have separate switches for what the API calls "user mode" and "active program".

Ideally, we would have some kind of multilevel switch entity model, but this unfortunately does not exist. The best alternative I can think of is two switches, program 1 active and program 2 active, where if you activate/deactivate one of the switches, it also changes state of the other switch (not explicitly).

**Comment by ksya** [comment]
Not a fan of your last proposal. I think its better to implement it as a service then. Users can then make a selectbox if they want for the service.

What do you think of adding holiday mode and fireplace mode to the presets? When those are active, clock is actually disabled as well.

**Comment by RobBie1221** [comment]
> Not a fan of your last proposal. I think its better to implement it as a service then. Users can then make a selectbox if they want for the service.

That's also an option, then at least users can automate around it.

> What do you think of adding holiday mode and fireplace mode to the presets? When those are active, clock is actually disabled as well.

I'm not a big fan of that either for two reasons. One is that the climate entity is basically as simple w.r.t. options as the display of the device and the frontpage of the app. It's easy to understand and consistent with the UI of the device. The other is that those use other endpoints. It would add complexity to the entity, the code gets more complex and thus less readible.

I'm pretty ok with the way fireplace and holiday mode work and are implemented. But it's off course just my opinion.

**Comment by RobBie1221** [comment]
My opinion is by the way not so strong on the fireplace and holiday thing :p

**Comment by RobBie1221** [comment]
I do wonder, what would happen if you combine fireplace with manual mode? I'd expect it to respect manual mode?

**Comment by RobBie1221** [comment]
@ksya I see a new entity model has been added since Dec. 2020, a number entity. This would allow a user to set a number within a predefined min/max range with predefined step size. We could change the active program entity to be a number entity. That would not only show the actual value but also allow the user to change it.

**Comment by RobBie1221** [comment]
Closing this, a selector entity model was introduced, with this model we can make a selection entity to pick between Clock 1 and Clock 2.

**Pull request closed without merging**
