### PR TITLE
Add config flow step user and device info

### PR DESCRIPTION
**Pull request by RobBie1221**
- Add config flow step user
- Add device info

### CODE REVIEW

**Comment by ksya** [comment]
Great work! I have updated the integration, but did not have all sensors and switches enabled. After I restarted HA, I removed the config from the configuration.yaml and restarted again. I still do not see a way to add the missing sensors again. I think I must remove the integration and add it again for this to work, or is there another way?

**Comment by RobBie1221** [comment]
Maybe some details, when you add the integration to the UI, it will add all sensors/switches. Once you have a configuration.yaml key, it will override the data in the ConfigEntry. If you had a key in configuration.yaml which contained a selection of sensors/switches, there are three ways to change this:
1. Remove the integration and re-add through UI (you'll get all sensors/switches then)
2. Re-add or change the settings in configuration.yaml, this will override data in the ConfigEntry
3. Manually edit core.config_entries in the .storage folder (this is the most user-unfriendly way)

**Comment by ksya** [comment]
That last one did the trick! Thanks for that. I think we must add that to the readme

**Comment by RobBie1221** [comment]
I would not advice editing core.config_entries in a manual, we need a better way to handle that.

First thing we need to decide on is whether we would want to keep the option to make a selection between sensors and switches or just create them all. Currently, if you solely use UI, you get them all with no option to make a selection. If that is not the preferred way, we need an alternative.

**Comment by ksya** [comment]
I think what must be done is that the sensors/switch config must be ignored when updating to this new version with config flow. After that the user can disable entities it does not want.

**Comment by RobBie1221** [comment]
Yes, so that's basically the second option. Always add them all and ignore the configuration.

I will take that into account with the next pull. I refactored the data fetching to a DataUpdateCoordinator, that makes the fetching a lot cleaner as it's done from one places and uses standard mechanisms available in the entity models. I do have to see how we can prevent API data being fetched in that case when entities are disabled.

**Comment by ksya** [comment]
I think the not calling the api when a entity is disabled already works:
"When disabled_by is set to a string value, the entity will not be added to Home Assistant when the integration passes it to async_add_entities."

And I see no entries ("async_update called for *") in the log.

Right now I'm struggling with adding more sensors to const.py, which do not automatically come up in the UI

**Pull request merged**
