### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JCPvanHooren**
Because I kept running into somewhat unclear descriptions of sensors and switches, I'd suggest to extend the README.
Happy to refine when I run into more values/options/etc...
I've taken as many descriptions from the (Android) app as possible (quotes in double quotes).

### CODE REVIEW

**Comment by JCPvanHooren** [comment]
Done.
BTW, I'm missing knowledge or code to complete all fields.
e.g.:
- I don't know all possible value for 'Hot water operation' and cannot find anything in the code that would help).
- I don't have (at least not in my instance) 'actual_power', but it does exist in the code

**Comment by RobBie1221** [comment]
> * I don't have (at least not in my instance) 'actual_power', but it does exist in the code

Leaving it empty is fine for now, at least this is more explanation then there was :)

**Comment by JCPvanHooren** [comment]
> > * I don't have (at least not in my instance) 'actual_power', but it does exist in the code
> 
> Leaving it empty is fine for now, at least this is more explanation then there was :)

That was my thinking as well.
One that really puzzles me, and if you have more info, I'd appreciate it, is 'preheat'.
There's a 'hot_water', which I believe controls preheating of hot water.
There's also a 'preheating', which I have no clue what it does. Do you know?

**Comment by RobBie1221** [comment]
Some thing don't work really as I would expect it. Challenge is that it uses an "unofficial API".

This is all documentation I have ever seen:
https://github.com/marcelrv/nefit_easy_protocol/blob/master/Endpoints.md

**Pull request merged**
